### ISSUE TITLE
10/31 Build Target Not Moving 

### ISSUE THREAD

**Issue by nlanter95** [mtu-most/franklin#25] opened 2016-11-30 01:05 UTC
When I type in values or use the arrow keys on the target boxes under position the print location stays the same and does not move. Changing the angle still works.

**Comment by wijnen** [comment] 2017-05-29 15:59
This works for me, I don't remember if I fixed anything for this.  Can you confirm whether this is still a problem for you?

**Comment by wijnen** [comment] 2017-07-04 18:22
I did reproduce this problem, I think.  It has been fixed in the latest version on github.

**Closed as completed by wijnen** 2017-07-04 18:22 UTC
