### ISSUE TITLE
Drag to position doesn't work with angle other than zero

### ISSUE THREAD

**Issue by gcanzalo** [mtu-most/franklin#26] opened 2017-01-02 20:13 UTC
The mouse dragging feature does not work if the Delta Position Angle is other than zero.

**Comment by wijnen** [comment] 2017-05-29 16:09
I cannot reproduce this; can you confirm that it is still happening?

**Comment by wijnen** [comment] 2017-07-04 18:22
I fixed something that was probably the cause of this, so I'm closing the issue.  Please reopen if it's still a problem with the latest version.

**Closed as completed by wijnen** 2017-07-04 18:22 UTC
